server-read: irc.libera.chat:+6697
password-read: thermite:hunter2
server-write: irc.libera.chat:+6697
password-write: thermite:hunter3
channel: "##thermite"
pinned-cert: abc123

database:
  user: jess
  name: thermite
  # optional
  #pass: hunter4
  # optional
  #host: 127.0.0.1

pipe-name: "##thermite-????????"
make-pipe:
  - 'MODE {TARGET} +PisI-c *!*@{HOSTNAME}'
  - 'PRIVMSG chanserv :register {TARGET}'
  - 'PRIVMSG chanserv :flags {TARGET} *!*@{HOSTNAME} +V'

  
