server: irc.libera.chat:+6697
password: thermite:hunter2
channel: "##thermite"

database:
  user: jess
  name: thermite
  # optional
  #pass: hunter5
  # optional
  #host: 127.0.0.1

pipe-name: "##thermite-????????"
make-pipe:
  - 'MODE {TARGET} +PisI-c *!*@{HOSTNAME}'
  - 'PRIVMSG chanserv :register {TARGET}'
  - 'PRIVMSG chanserv :flags {TARGET} *!*@{HOSTNAME} +V'

  
